// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

 static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBhGpxjXWR5jPFQGMK4ZAN_zQUd_kmNEU',
    appId: '1:65652715036:web:YOUR_WEB_APP_ID_HERE',
    messagingSenderId: '65652715036',
    projectId: 'patelrmartnotifications',
    authDomain: 'patelrmartnotifications.firebaseapp.com',
    storageBucket: 'patelrmartnotifications.appspot.com',
  );

 static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyCBhGpxjXWR5jPFQGMK4ZAN_zQUd_kmNEU',
  appId: '1:65652715036:android:12118f78c4d70d859cb9d9',
  messagingSenderId: '65652715036',
  projectId: 'patelrmartnotifications',
  storageBucket: 'patelrmartnotifications.appspot.com',
);

   static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBhGpxjXWR5jPFQGMK4ZAN_zQUd_kmNEU',
    appId: '1:65652715036:ios:YOUR_IOS_APP_ID_HERE',
    messagingSenderId: '65652715036',
    projectId: 'patelrmartnotifications',
    storageBucket: 'patelrmartnotifications.appspot.com',
    iosBundleId: 'com.patelrmart.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBhGpxjXWR5jPFQGMK4ZAN_zQUd_kmNEU',
    appId: '1:65652715036:ios:YOUR_IOS_APP_ID_HERE',
    messagingSenderId: '65652715036',
    projectId: 'patelrmartnotifications',
    storageBucket: 'patelrmartnotifications.appspot.com',
    iosBundleId: 'com.patelrmart.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBhGpxjXWR5jPFQGMK4ZAN_zQUd_kmNEU',
    appId: '1:65652715036:web:YOUR_WEB_APP_ID_HERE',
    messagingSenderId: '65652715036',
    projectId: 'patelrmartnotifications',
    authDomain: 'patelrmartnotifications.firebaseapp.com',
    storageBucket: 'patelrmartnotifications.appspot.com',
  );
}
